---
title: "HW4"
author: "Erik Andersen"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    keep_md: yes
  always_allow_html: true
---

### Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
```

```{r}
here::i_am("HW4/HW4.Rmd")

# Load packages
pacman::p_load(tidyverse, magrittr, estimatr, fixest, plm, systemfit, tidysynth)
```

```{r}
# Load data
election_df = haven::read_dta(here::here("HW4", "data", "GriffithNoonen2022_Econ587.dta"))
```

### Question 1

Note: lm_robust and feols seem to calculate clustered standard errors differently. Feols matches those from the paper, but I've use both based on convenience and when I don't have a standard error to match I defer to lm_robust. 

#### a)

```{r data}
# Generate treatment dummy and city/cycle pair for clustering
election_df %<>% mutate(post = if_else(cycle >= 2017, 1, 0), 
                        treatment = if_else(city == 'Seattle', 1, 0),
                        city_cycle = as.factor(city):as.factor(cycle),
                        seattle = if_else(city == 'Seattle', 1, 0))

# Run naive regression
election_df %>% lm_robust(candidates_ballot ~ treatment + At_Large*Special,., clusters = city_cycle)
```

#### b)

```{r, dependson='data'}
# Before and after treatment for seattle
(before_after_seattle = election_df |> filter(city == 'Seattle') %>%
  lm_robust(candidates_ballot ~ post + At_Large*Special,., clusters = city_cycle))

# Before and after for non-seattle cities
(before_after_other = election_df |> filter(city != 'Seattle') %>%
  lm_robust(candidates_ballot ~ post + At_Large*Special,., clusters = city_cycle))

# Diff between
summary(before_after_seattle)$coefficients[2,1] - summary(before_after_other)$coefficients[2,1]
```

#### c)

```{r, dependson='data'}
# Cross sectional estimate before 2017
(cross_before = election_df |> filter(post == 0) %>%
  lm_robust(candidates_ballot ~ seattle + At_Large*Special,., clusters = city_cycle))

# Cross-Sectional Estimate after 2017
(cross_after = election_df |> filter(post == 1) %>%
  lm_robust(candidates_ballot ~ seattle + At_Large*Special,., clusters = city_cycle))

# Diff between
summary(cross_after)$coefficients[2,1] - summary(cross_before)$coefficients[2,1]

```


#### d)

```{r, dependson='data'}
# Diff-in-Diff
(diff_in_diff = election_df %>% lm_robust(candidates_ballot ~ post*treatment + At_Large*Special,., clusters = city_cycle)) # 2.8

# Coeff of interest is post:treatment
```

#### e)

```{r, dependson='data'}
# two way fixed effects. We're switching regression functions here because it has prettier output, and seems to calculate standard errors in a slightly different way that matches the paper
(two_way = election_df %>% feols(candidates_ballot ~ post*treatment | as.factor(city) + as.factor(cycle) + At_Large*Special,., cluster = "city_cycle"))# Point estimate and se match

# Coeff of interest is post:treatment
```

#### f)

```{r, dependson='data'}
# Test for parallel pre-trends with city fixed effects
election_df |> filter(post == 0 ) |> 
  mutate(`cycle*seattle` = cycle*seattle) %>%
  lm_robust(candidates_ballot ~ `cycle*seattle` + At_Large*Special + as.factor(city),., clusters = city_cycle)

# Without city fixed effects
election_df |> filter(post == 0 ) |> 
  mutate(`cycle*seattle` = cycle*seattle) %>%
  lm_robust(candidates_ballot ~ `cycle*seattle` + At_Large*Special,., clusters = city_cycle)
```

#### g)

```{r, dependson='data'}
# Estimate non-parallel trends test
election_df |> mutate(`seattle*cycle` = seattle*cycle, `seattle*post` = seattle*post) %>%
  feols(candidates_ballot ~ cycle +  `seattle*cycle` + `seattle*post` + At_Large*Special + as.factor(city),., cluster = "city_cycle")

# Coef of interest is seattle*post
```

#### h)

```{r, dependson='data'}
# Run part g again but only with cities in washington
election_df |> filter(state == 'Wash') |> 
  mutate(`seattle*cycle` = seattle*cycle, `seattle*post` = seattle*post) %>%
  feols(candidates_ballot ~ cycle +  `seattle*cycle` + `seattle*post` + At_Large*Special + as.factor(city),., cluster = "city_cycle")

# Now just with california cities
election_df |> filter(state == "Calif" | city == 'Seattle') |> 
  mutate(`seattle*cycle` = seattle*cycle, `seattle*post` = seattle*post) %>%
  feols(candidates_ballot ~ cycle +  `seattle*cycle` + `seattle*post` + At_Large*Special + as.factor(city),., cluster = "city_cycle")
```

### Question 2

#### Part b)

```{r}
# First we have to refine the models as the appropriate type of object because r is kinda stupid
diff_in_diff_plm = election_df %>% plm(candidates_ballot ~ post*treatment + At_Large*Special,.)
two_way_plm = election_df %>% feols(candidates_ballot ~ post*treatment + as.factor(city) + as.factor(cycle) + At_Large*Special,.)

# Test with phtest from plm
plm::phtest(diff_in_diff_plm, two_way_plm)
```

#### Part c)

```{r}

```



























### Question 3

```{r balance}
# Collapse by city_cycle 
balanced_df = election_df |> 
  mutate(cycle = factor(election_df$cycle, labels = 1:10), # Renumber cycles 1 through 10
         city_cycle = as.factor(city):as.factor(cycle)) |> # Remake this variable using new numbering
  group_by(city_cycle) |> 
  summarise(candidates_ballot = mean(candidates_ballot, na.rm = T),
            post = mean(post, na.rm = T),
            treatment = mean(treatment, na.rm = T),
            At_Large = mean(At_Large, na.rm = T),
            Special = mean(Special, na.rm = T),
            seattle = mean(seattle, na.rm = T),
            Pct_general = mean(Pct_general, na.rm = T),
            inc_run = mean(inc_run, na.rm = T),
            inc_win = mean(inc_win, na.rm = T),
            inc_pct_general = mean(inc_pct_general, na.rm = T),
            Votes_total_general = mean(Votes_total_general, na.rm = T),
            donors = mean(donors, na.rm = T),
            total_Less200 = mean(total_Less200, na.rm = T),
            donors_Less200  = mean(donors_Less200, na.rm = T),
            pop = mean(pop, na.rm = T),
            pop100k = mean(pop100k, na.rm = T),
            state = unique(state)) |> 
  mutate(city = stringr::word(city_cycle, sep = ":"),
         cycle = as.numeric(stringr::word(city_cycle, start = -1, sep = ":")))

```

#### a)

```{r, dependson='balance'}
(balanced_dd = balanced_df %>% lm_robust(candidates_ballot ~ post*treatment + At_Large*Special,., clusters = city_cycle)) # 3.1
```

#### b)

```{r, dependson='balance'}
(balanced_two = balanced_df %>% feols(candidates_ballot ~ post*treatment | as.factor(city) + as.factor(cycle) + At_Large*Special,., cluster = "city_cycle"))
```

#### c)

```{r synth, dependson='balance'}
# Generate synthetic object
all_synth = balanced_df |> synthetic_control(outcome = candidates_ballot,
                                 unit = city,
                                 time = cycle,
                                 i_unit = 'Seattle',
                                 i_time = 8) |> 
  # I can only use these predictors because for pretty much all other values there are some city/cycles where there are no observations which breaks this
  generate_predictor(At_Large = At_Large, 
                     Special = Special,
                     Pct_general = Pct_general,
                     inc_run = inc_run,
                     inc_win = inc_win,
                     inc_pct_general = inc_pct_general,
                     pop = pop,
                     pop100k = pop100k) |> 
  generate_weights() |> generate_control() 
```

```{r, dependson="synth"}
plot_weights(all_synth)
grab_unit_weights(all_synth) |> arrange(desc(weight))
plot_trends(all_synth)
```


#### d)

```{r synth_wash}
# Generate synthetic control for only cities in washington
washington_synth = balanced_df |> filter(state == 'Wash') |> 
  synthetic_control(outcome = candidates_ballot,
                                 unit = city,
                                 time = cycle,
                                 i_unit = 'Seattle',
                                 i_time = 8) |> 
  generate_predictor(At_Large = At_Large, # I had to remove special because there's no variation in it for washington
                     Pct_general = Pct_general,
                     inc_run = inc_run,
                     inc_win = inc_win,
                     inc_pct_general = inc_pct_general,
                     pop = pop,
                     pop100k = pop100k) |> 
  generate_weights() |> generate_control() 
```

```{r, dependson='synth_wash'}
plot_weights(washington_synth)
grab_unit_weights(washington_synth) |> arrange(desc(weight))
plot_trends(washington_synth)
```

#### e)

```{r synth_calif}
# Generate synthetic control for only cities in washington
california_synth = balanced_df |> filter(state == 'Calif' | city == 'Seattle') |> 
  synthetic_control(outcome = candidates_ballot,
                                 unit = city,
                                 time = cycle,
                                 i_unit = 'Seattle',
                                 i_time = 8) |> 
  generate_predictor(Pct_general = Pct_general,
                     inc_run = inc_run,
                     inc_win = inc_win,
                     inc_pct_general = inc_pct_general,
                     pop = pop,
                     pop100k = pop100k) |> 
  generate_weights() |> generate_control() 
```

```{r, dependson='synth_calif'}
plot_weights(california_synth)
grab_unit_weights(california_synth) |> arrange(desc(weight))
plot_trends(california_synth) 
```

#### f)

```{r synth_placebo}
# Drop Seattle and generate placebos
placebos_synth = balanced_df |> 
  synthetic_control(outcome = candidates_ballot,
                                 unit = city,
                                 time = cycle,
                                 i_unit = 'Seattle',
                                 i_time = 8,
                                 generate_placebos = T) |> 
  generate_predictor(At_Large = At_Large, # I had to remove special because there's no variation in it for washington
                     Pct_general = Pct_general,
                     inc_run = inc_run,
                     inc_win = inc_win,
                     inc_pct_general = inc_pct_general,
                     pop = pop,
                     pop100k = pop100k) |> 
  generate_weights() |> generate_control() 
```

```{r, dependson='synth_placebo'}
plot_placebos(placebos_synth)
```










