---
title: "HW5"
author: "Erik Andersen"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
```

```{r}
here::i_am("HW5/HW5.Rmd")

# Load packages
pacman::p_load(tidyverse, magrittr, rdd, ivreg)
```

```{r data}
# Load data
oz_df = haven::read_dta(here::here('HW5', "data", "Ozier_JHR_Econ587.dta"))
```

### Question 1

#### a)

```{r clean_data, dependson='data'}
# Generate indicator for treatment status. Treated if test > 0
oz_df = oz_df |>  mutate(treatment = if_else(test > 0, 1, 0))

# Regress secondary on test score, treatment, and interaction
oz_df %>% lm(secondary ~ test*treatment,.) |> broom::tidy()
```

#### c)

```{r, dependson='clean_data'}
# Define restrictions
restrict = c(0.8, 0.4, 0.2, 0.1)

lapply(restrict, function(x){
  oz_df |> filter(abs(test) < x) %>%
    lm(secondary ~ test*treatment,.) |> 
    broom::tidy()
})
```

#### d)

```{r, dependson='clean_data'}
# Estimate rdd. Note default standard errors are heteroskedastic robust
RDestimate(secondary ~ test, oz_df, cutpoint = 0) 
```

#### e)

```{r, dependson='clean_data'}
# Plot rdd graph
oz_df |> group_by(a = cut(test, 26)) |> 
  summarise(secondary=mean(secondary), test = mean(test)) |> 
  ggplot(aes(test, secondary)) + 
    geom_point() + 
    geom_smooth(data = oz_df |> filter(test > 0), method = 'lm', col = 'black') +
    geom_smooth(data = oz_df |> filter(test < 0), method = 'lm', col = 'black') +
    geom_vline(xintercept = 0, lty = 5) + 
    xlab("Test Score") + ylab("Probability of Completing\n Secondary School") + 
    cowplot::theme_cowplot()
ggsave(here::here("HW5", "rdd_plot.pdf"))
```

#### f)

```{r, dependson='clean_data'}
# Rerun esimation of rdd, but override default kernal and bandwidths
RDestimate(secondary ~ test, oz_df, cutpoint = 0, kernel = 'rectangular', bw = 0.8)
```

#### g)

```{r, dependson='clean_data'}
ivreg(rv ~ secondary + test + female + test:treatment | 
        treatment + test + female + test:treatment, data = oz_df) |> broom::tidy()
```

#### h)

```{r,dependson='clean_data'}
# Run estimate again, but use controls. Note the regressors are in the opposite order than the homework suggests. This is because the package wants the variables in the order running variable + endogenous treatment.
RDestimate(rv ~ test + secondary, oz_df, cutpoint = 0)
```

#### i)

```{r, dependson='clean_data'}
# Replicate g result. I don't include test interacted with treatment because it gives insane results like the LATE is 20 and I don't know why
RDestimate(rv ~ test + secondary | female , data = oz_df, cutpoint = 0,
           kernel = 'rectangular', bw = 0.6)
```

### Question 2

```{r simdata}
# Load data
sim_df = haven::read_dta(here::here("HW5", "data", "RD_Manip_Econ587.dta"))
```

#### a)

```{r}
# Plot kernel densities for all four measures of wealth for bandwidths 0.1, 0.05, 0.01
lapply(c(0.1, 0.05, 0.01),
       function(x) {
         sim_df |> ggplot(aes(reportwealth1)) +
           geom_density(bw = x) +
           geom_density(aes(reportwealth2), bw = x, col = 'red') +
           geom_density(aes(reportwealth3), bw = x, col = 'blue') +
           geom_density(aes(reportwealth4), bw = x, col = 'green') +
           xlab("Wealth Kernel Density") + ylab("") +
           ggtitle(paste("Wealth Kernel Density with Bandwidth =", x)) +
           labs(caption = "Black: Reported Wealth 1\n Red: Reported Wealth 2\n
                Blue: Reported Wealth 3\n Green: Reported Wealth 4") +
           cowplot::theme_cowplot()
         ggsave(here::here("HW5", paste(
           "Kernel_wealth_bandwidth_", x, ".pdf", sep = ""
         )))
       }
)
```

#### b)



```{r}
# Test smoothness around the cuttoff using ocular methods. Unfortunately to loop this over the four scenarios requires nonstandard evaluation which I haven't currently figured
bandwidths = c(0.1, 0.01, 0.05)

lapply(bandwidths, function(x){
  sim_df |> filter(abs(reportwealth1) < x) |> 
    select(reportwealth1)|>
    ggplot(aes(reportwealth1)) +
        geom_histogram(bins = 10) + 
        geom_vline(xintercept = 0, color = 'red', lwd = 3) +
        xlab("Report 1") + ylab("") + cowplot::theme_cowplot()
})

lapply(bandwidths, function(x){
  sim_df |> filter(abs(reportwealth2) < x) |> 
    select(reportwealth2)|>
    ggplot(aes(reportwealth2)) +
        geom_histogram(bins = 10) + 
        geom_vline(xintercept = 0, color = 'red', lwd = 3)+
        xlab("Report 2") + ylab("")+ cowplot::theme_cowplot()
})

lapply(bandwidths, function(x){
  sim_df |> filter(abs(reportwealth3) < x) |> 
    select(reportwealth3)|>
    ggplot(aes(reportwealth3)) +
        geom_histogram(bins = 10) + 
        geom_vline(xintercept = 0, color = 'red', lwd = 3)+
        xlab("Report 3") + ylab("")+ cowplot::theme_cowplot()
})

lapply(bandwidths, function(x){
  sim_df |> filter(abs(reportwealth4) < x) |> 
    select(reportwealth4)|>
    ggplot(aes(reportwealth4)) +
        geom_histogram(bins = 10) + 
        geom_vline(xintercept = 0, color = 'red', lwd = 3)+
        xlab("Report 4") + ylab("")+ cowplot::theme_cowplot()
})
```

#### c)

```{r}
# McCrary kovac test
vars = paste0("reportwealth", 1:4)

# P-values are reported
sapply(vars, function(x){
  DCdensity(sim_df[[x]], cutpoint = 0)
})

```

#### d)

```{r}
# Generate treatment variables equal to one if repored wealth is below 0
sim_df %<>% mutate(treat1 = if_else(reportwealth1 < 0, 1, 0),
                   treat2 = if_else(reportwealth2 < 0, 1, 0),
                   treat3 = if_else(reportwealth3 < 0, 1, 0),
                   treat4 = if_else(reportwealth4 < 0, 1, 0))

# For each reported wealth generate the following 
# new-wealth = true-wealth + 0.2*treat + e    e ~ N(0, 0.01)
sim_df %<>% mutate(new_wealth1 = truewealth + 0.2 * treat1 + rnorm(nrow(sim_df), 0, sqrt(0.01)),
                   new_wealth2 = truewealth + 0.2 * treat2 + rnorm(nrow(sim_df), 0, sqrt(0.01)),
                   new_wealth3 = truewealth + 0.2 * treat3 + rnorm(nrow(sim_df), 0, sqrt(0.01)),
                   new_wealth4 = truewealth + 0.2 * treat4 + rnorm(nrow(sim_df), 0, sqrt(0.01)))

# Summarize the new wealths
lapply(1:4, function(i){
  pdf(here::here("HW5", paste0("new-wealth", i, ".pdf")))
  plot(c(sim_df[paste0("reportwealth", i)]) |> unlist(), 
       c(sim_df[paste0('new_wealth', i)]) |> unlist(),
       xlab = paste0("Report Wealth", i),
       ylab = paste0("New Wealth", i))
  dev.off()
})

```

#### e)

```{r}
lapply(1:4, function(i){ 
  
  # Generate formula
  y = paste0("new_wealth", i)
  treat = paste0("treat", i)
  report = paste0("reportwealth", i)
  x = paste(treat, report, sep = "*")
  formula = paste(y, x, sep = "~")

  # Run regression
  lm(formula, sim_df) |> summary()
})
```


#### f)

```{r}
lapply(1:4, function(i){
  
  # Generate formula
  y = paste0("new_wealth", i)
  x = paste0("reportwealth", i)
  formula = paste(y, x, sep = "~")
  
  # Run rdd 
  RDestimate(formula, sim_df)
})
```







